### ISSUE TITLE
Grace note slash the wrong size?

### ISSUE THREAD

**Issue by dbenjaminmiller** [tr-igem/ekmelos#4]
Not sure if this is an issue with the font itself or esmuflily. When using esmuflily, Ekmelos' slash on grace notes is of the correct size:

<img width="480" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/30d19e3a-7f24-4e0d-ab7f-68c65fc32ded">

However, using another font causes the slash to appear too big. This occurs with all the non-Ekmelos SMUFL fonts I try, so I get the feeling that it may be a problem with the Ekmelos font not matching many other SMUFL fonts, and esmuflily matching Ekmelos' peculiar sizing, and/or fixed sizing used in esmuflily when the glyph might be of different sizes...

Examples...

Sebastian:

<img width="512" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/72dde81f-86e3-4fad-91d5-ad0123e8879e">

Bravura:

<img width="530" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/22c7a2b8-2f24-4b7a-960b-215b70cd2f6d">

Finale Engraver:

<img width="495" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/2582cf95-e049-462c-8bca-d69490179027">

Finale Maestro:

<img width="491" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/422901ab-7e7a-4b0f-a7bb-99b088b4041e">

Finale Legacy:

<img width="399" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/95b7138d-f850-46a9-95b3-88af334c288d">

Leland, though, seems to be OK enough, although the slash is still bigger than Ekmelos':

<img width="437" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/fc255752-7888-4543-bcfa-3e3db9b825a9">

But if we use Leland with MuseScore, we see the slash is actually apparently not rendered using this glyph, which is perhaps an issue anyway:

<img width="537" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/fcdde6dd-1877-4abc-b813-d056e5f869ad">

**Comment by dbenjaminmiller** [comment]
<img width="98" alt="image" src="https://github.com/tr-igem/ekmelos/assets/43855846/ef2fdd31-ff53-48ed-9026-b9512dd713c5">
with fonts other than Ekmelos, the slashes look fine when changing from `make-fontsize-markup 3` to `make-fontsize-markup 0` in the relevant spot in esmuflily.

**Comment by tr-igem** [comment]
Yes it is much too small and I erroneously set an extra font size +3 in esmuflily. I was focused only on ekmelos.
